### ISSUE TITLE
[FE] 현재 게임방에 참여한 사용자 이름 정보를 화면에 표시하는 기능

### ISSUE THREAD

**Issue by 0Chord** [boostcampwm-2024/web12-MafiaCamp#54]
## ❓ 어떤 기능인가요?

- 소켓을 통해 전달 받은 현재 게임방에 참여한 사용자 이름 정보를 화면에 표시합니다.

## 📝 기능 설명

- 실시간으로 사용자 이름 정보를 게임방에 참여한 사용자 모두에게 전달하여 화면에 표시합니다.

## ✅ TODO

구현해야 하는 기능에 대해 체크리스트를 작성해 주세요.

- [ ] TODO 1
- [ ] TODO 2

## 📚 참고할만한 자료(선택)

- 추가적으로 참고할 만한 사항이 있으면 적어주세요.
- 없는 경우 해당 단락을 삭제해 주세요.

**Comment by HyunJinNo** [comment]
#47 과 중복되므로 해당 Issue를 Close하였습니다.
